name: Docs

# We document the main branch
on:
  push:
    branches: [ main ]  
env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3       
    - name: install mdbook
      run: cargo install mdbook
    - name: build book
      run: mdbook build
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: book # The folder the action should deploy.
